export { default as DashboardPage } from './DashboardPage.vue'
export { default as UsersPage } from './UsersPage.vue'
export { default as PrestatairePage } from './PrestatairePage.vue'
export { default as CategoriesPage } from './CategoriesPage.vue'
export { default as EventsPage } from './EventsPage.vue'
export { default as LogsPage } from './LogsPage.vue'
export { default as DepositRequestsPage } from './DepositRequestsPage.vue'
export { default as SettingsPage } from './SettingsPage.vue'
export { default as TalksPage } from './TalksPage.vue'
export { default as ProjectsPage } from './ProjectsPage.vue'
export { default as TrainingsPage } from './TrainingsPage.vue'
export { default as ObjectsPage } from './ObjectsPage.vue'

// Staff (animateurs / formateurs)
export { default as MyTrainingsPage } from './staff/MyTrainingsPage.vue'
export { default as PlanningPage } from './staff/PlanningPage.vue'
export { default as AdvicePage } from './staff/AdvicePage.vue'
export { default as ModerationPage } from './staff/ModerationPage.vue'
