export { default as DashboardPage } from './DashboardPage.vue'
export { default as UsersPage } from './UsersPage.vue'
export { default as PrestatairePage } from './PrestatairePage.vue'
export { default as CategoriesPage } from './CategoriesPage.vue'
export { default as EventsPage } from './EventsPage.vue'
export { default as LogsPage } from './LogsPage.vue'
export { default as DepositRequestsPage } from './DepositRequestsPage.vue'
export { default as SettingsPage } from './SettingsPage.vue'
